### ISSUE TITLE
Invisible notification window gets enumerated

### ISSUE THREAD

**Issue by nir9** [prabirshrestha/dwm-win32#32]
Some times dwm-win32 grabs an invisible notification window on Windows 10 and then it is enumerated when moving between windows, even though it is invisible

**Comment by prabirshrestha** [comment]
This has been irritating me. I haven't bothered to fix it yet since hadn't had time. I added a special `writelog` key binding. If you try [v0.0.15](https://github.com/prabirshrestha/dwm-win32/releases/tag/v0.0.15) release and you hit this please try `mod+control+l` and it should write a file called `dwm-win32.log` which should contain the state of the windows. Feel free to paste it here on the one that you think shouldn't be shown. I will do the same if I see it. I need to figure out what the client is so that I can ignore it.

**Comment by nir9** [comment]
Thanks :) I am gonna try working as well on a more general solution as well, because there might be more cases like this with other invisible windows and it's definitely a bug

**Comment by prabirshrestha** [comment]
It is a bug, I'm not sure where since I haven't debuged much. It could be due to race conditions.

Sometime I quite dwm-win32 and start again and it no longer considers it visible which means I could add a hotkey to recompute or automatically do it when windows get rearranged. I want to look at logs before I add the hack.

**Comment by nir9** [comment]
@prabirshrestha Yah I do that as well XD, it is interesting it is caught since I am pretty sure there are checks for visibility of windows before catching them, looking into this RN :)

**Comment by prabirshrestha** [comment]
#33 Merged.
